(function () {
  function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

  function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

  function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }

  (window["webpackJsonp"] = window["webpackJsonp"] || []).push([[32], {
    /***/
    "B4io":
    /*!*********************************************************************************!*\
      !*** ./src/app/vsan/common/component/cell/health-mor-cell.scss.shim.ngstyle.js ***!
      \*********************************************************************************/

    /*! exports provided: styles */

    /***/
    function B4io(module, __webpack_exports__, __webpack_require__) {
      "use strict";

      __webpack_require__.r(__webpack_exports__);
      /* harmony export (binding) */


      __webpack_require__.d(__webpack_exports__, "styles", function () {
        return styles;
      });
      /**
       * @fileoverview This file was generated by the Angular template compiler. Do not edit.
       *
       * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes,extraRequire}
       * tslint:disable
       */


      var styles = ["[_nghost-%COMP%] {\n  white-space: nowrap;\n  display: flex;\n  flex: 1 0 0rem;\n  align-items: center;\n}\nclr-icon[_ngcontent-%COMP%] {\n  flex: 0 0 auto;\n}\na[_ngcontent-%COMP%] {\n  display: inline-block;\n}\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvdnNhbi9jb21tb24vY29tcG9uZW50L2NlbGwvaGVhbHRoLW1vci1jZWxsLnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsaUZBQUE7QUFDQTtFQUNHLG1CQUFBO0VBQ0EsYUFBQTtFQUNBLGNBQUE7RUFDQSxtQkFBQTtBQUNIO0FBRUE7RUFDRyxjQUFBO0FBQ0g7QUFHQTtFQUNHLHFCQUFBO0FBQUgiLCJmaWxlIjoic3JjL2FwcC92c2FuL2NvbW1vbi9jb21wb25lbnQvY2VsbC9oZWFsdGgtbW9yLWNlbGwuc2NzcyIsInNvdXJjZXNDb250ZW50IjpbIi8qIENvcHlyaWdodCAyMDE3LTIwMjEgVk13YXJlLCBJbmMuIEFsbCByaWdodHMgcmVzZXJ2ZWQuIC0tIFZNd2FyZSBDb25maWRlbnRpYWwgKi9cbjpob3N0IHtcbiAgIHdoaXRlLXNwYWNlOiBub3dyYXA7XG4gICBkaXNwbGF5OiBmbGV4O1xuICAgZmxleDogMSAwIDByZW07XG4gICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuXG5jbHItaWNvbiB7XG4gICBmbGV4OiAwIDAgYXV0bztcbn1cblxuLy8gbmVlZGVkIHRvIGNvcnJlY3RseSBwb3NpdGlvbiB0aGUgdnNhbi1zaG93LXRpdGxlXG5hIHtcbiAgIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbn0iXX0= */"];
      /***/
    },

    /***/
    "PZM+":
    /*!***********************************************************************************!*\
      !*** ./src/app/vsan/common/component/cell/health-mor-cell.component.ngfactory.js ***!
      \***********************************************************************************/

    /*! exports provided: RenderType_HealthMorCellComponent, View_HealthMorCellComponent_0, View_HealthMorCellComponent_Host_0, HealthMorCellComponentNgFactory */

    /***/
    function PZM(module, __webpack_exports__, __webpack_require__) {
      "use strict";

      __webpack_require__.r(__webpack_exports__);
      /* harmony export (binding) */


      __webpack_require__.d(__webpack_exports__, "RenderType_HealthMorCellComponent", function () {
        return RenderType_HealthMorCellComponent;
      });
      /* harmony export (binding) */


      __webpack_require__.d(__webpack_exports__, "View_HealthMorCellComponent_0", function () {
        return View_HealthMorCellComponent_0;
      });
      /* harmony export (binding) */


      __webpack_require__.d(__webpack_exports__, "View_HealthMorCellComponent_Host_0", function () {
        return View_HealthMorCellComponent_Host_0;
      });
      /* harmony export (binding) */


      __webpack_require__.d(__webpack_exports__, "HealthMorCellComponentNgFactory", function () {
        return HealthMorCellComponentNgFactory;
      });
      /* harmony import */


      var _health_mor_cell_scss_shim_ngstyle__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
      /*! ./health-mor-cell.scss.shim.ngstyle */
      "B4io");
      /* harmony import */


      var _angular_core__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
      /*! @angular/core */
      "8Y7J");
      /* harmony import */


      var _clr_angular__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(
      /*! @clr/angular */
      "X69f");
      /* harmony import */


      var _directive_icon_title_icon_title_directive__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(
      /*! ../../directive/icon-title/icon-title.directive */
      "wLY2");
      /* harmony import */


      var _util_reference_watcher__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(
      /*! ../../util/reference-watcher */
      "gyvr");
      /* harmony import */


      var _directive_show_title_show_title_directive__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(
      /*! ../../directive/show-title/show-title.directive */
      "XpuD");
      /* harmony import */


      var _angular_common__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(
      /*! @angular/common */
      "SVse");
      /* harmony import */


      var _health_mor_cell_component__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(
      /*! ./health-mor-cell.component */
      "uxYv");
      /* harmony import */


      var _service_navigation_navigation_service__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(
      /*! ../../service/navigation/navigation.service */
      "Qw2S");
      /**
       * @fileoverview This file was generated by the Angular template compiler. Do not edit.
       *
       * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes,extraRequire}
       * tslint:disable
       */


      var styles_HealthMorCellComponent = [_health_mor_cell_scss_shim_ngstyle__WEBPACK_IMPORTED_MODULE_0__["styles"]];

      var RenderType_HealthMorCellComponent = /*@__PURE__*/_angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵcrt"]({
        encapsulation: 0,
        styles: styles_HealthMorCellComponent,
        data: {}
      });

      function View_HealthMorCellComponent_1(_l) {
        return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 3, "clr-icon", [["size", "18"]], [[1, "shape", 0]], null, null, null, null)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](1, 16384, null, 0, _clr_angular__WEBPACK_IMPORTED_MODULE_2__["ClrIconCustomTag"], [], null, null), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](2, 4210688, null, 0, _directive_icon_title_icon_title_directive__WEBPACK_IMPORTED_MODULE_3__["IconTitleDirective"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ElementRef"]], null, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\n"]))], null, function (_ck, _v) {
          var _co = _v.component;
          var currVal_0 = _co.shape;

          _ck(_v, 0, 0, currVal_0);
        });
      }

      function View_HealthMorCellComponent_3(_l) {
        return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 16777216, null, null, 3, "span", [["vsan-show-title", ""]], [[4, "overflow", null], [4, "text-overflow", null], [4, "white-space", null]], null, null, null, null)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵprd"](131584, null, _util_reference_watcher__WEBPACK_IMPORTED_MODULE_4__["ReferenceWatcher"], _util_reference_watcher__WEBPACK_IMPORTED_MODULE_4__["ReferenceWatcher"], []), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](2, 4407296, null, 0, _directive_show_title_show_title_directive__WEBPACK_IMPORTED_MODULE_5__["ShowTitleDirective"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["ComponentFactoryResolver"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["Renderer2"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["NgZone"], _util_reference_watcher__WEBPACK_IMPORTED_MODULE_4__["ReferenceWatcher"]], null, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](3, null, ["\n      ", "\n   "])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](0, null, null, 0))], function (_ck, _v) {
          _ck(_v, 2, 0);
        }, function (_ck, _v) {
          var _co = _v.component;
          var currVal_0 = "hidden";
          var currVal_1 = "ellipsis";
          var currVal_2 = "nowrap";

          _ck(_v, 0, 0, currVal_0, currVal_1, currVal_2);

          var currVal_3 = _co.getMissingEntityLabel(_v.parent.context.$implicit);

          _ck(_v, 3, 0, currVal_3);
        });
      }

      function View_HealthMorCellComponent_5(_l) {
        return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 1, "span", [], null, null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](1, null, ["", ""]))], null, function (_ck, _v) {
          var _co = _v.component;

          var currVal_0 = _co.data.get(_v.parent.parent.context.$implicit);

          _ck(_v, 1, 0, currVal_0);
        });
      }

      function View_HealthMorCellComponent_7(_l) {
        return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 0, "span", [], [[8, "outerHTML", 1]], null, null, null, null))], null, function (_ck, _v) {
          var _co = _v.component;
          var currVal_0 = _co.COMMA_SEPARATOR;

          _ck(_v, 0, 0, currVal_0);
        });
      }

      function View_HealthMorCellComponent_6(_l) {
        return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 16777216, null, null, 6, "a", [["href", "javascript://"], ["vsan-show-title", ""]], [[4, "overflow", null], [4, "text-overflow", null], [4, "white-space", null]], [[null, "click"]], function (_v, en, $event) {
          var ad = true;
          var _co = _v.component;

          if ("click" === en) {
            var pd_0 = _co.navigateTo(_v.parent.parent.context.$implicit) !== false;
            ad = pd_0 && ad;
          }

          return ad;
        }, null, null)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵprd"](131584, null, _util_reference_watcher__WEBPACK_IMPORTED_MODULE_4__["ReferenceWatcher"], _util_reference_watcher__WEBPACK_IMPORTED_MODULE_4__["ReferenceWatcher"], []), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](2, 4407296, null, 0, _directive_show_title_show_title_directive__WEBPACK_IMPORTED_MODULE_5__["ShowTitleDirective"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["ComponentFactoryResolver"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["Renderer2"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["NgZone"], _util_reference_watcher__WEBPACK_IMPORTED_MODULE_4__["ReferenceWatcher"]], {
          copyToClipboard: [0, "copyToClipboard"]
        }, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](3, null, ["\n         ", "\n         "])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](16777216, null, null, 1, null, View_HealthMorCellComponent_7)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](5, 16384, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_6__["NgIf"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["TemplateRef"]], {
          ngIf: [0, "ngIf"]
        }, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\n      "])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](0, null, null, 0))], function (_ck, _v) {
          var _co = _v.component;
          var currVal_3 = true;

          _ck(_v, 2, 0, currVal_3);

          var currVal_5 = _co.showComma(_v.parent.parent.context.index);

          _ck(_v, 5, 0, currVal_5);
        }, function (_ck, _v) {
          var _co = _v.component;
          var currVal_0 = "hidden";
          var currVal_1 = "ellipsis";
          var currVal_2 = "nowrap";

          _ck(_v, 0, 0, currVal_0, currVal_1, currVal_2);

          var currVal_4 = _co.data.get(_v.parent.parent.context.$implicit);

          _ck(_v, 3, 0, currVal_4);
        });
      }

      function View_HealthMorCellComponent_4(_l) {
        return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 7, null, null, null, null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\n      "])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](16777216, null, null, 1, null, View_HealthMorCellComponent_5)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](3, 16384, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_6__["NgIf"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["TemplateRef"]], {
          ngIf: [0, "ngIf"]
        }, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\n      "])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](16777216, null, null, 1, null, View_HealthMorCellComponent_6)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](6, 16384, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_6__["NgIf"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["TemplateRef"]], {
          ngIf: [0, "ngIf"]
        }, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\n   "]))], function (_ck, _v) {
          var _co = _v.component;
          var currVal_0 = !_co.enableActionLink;

          _ck(_v, 3, 0, currVal_0);

          var currVal_1 = _co.enableActionLink;

          _ck(_v, 6, 0, currVal_1);
        }, null);
      }

      function View_HealthMorCellComponent_2(_l) {
        return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 7, null, null, null, null, null, null, null)), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\n   "])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](16777216, null, null, 1, null, View_HealthMorCellComponent_3)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](3, 16384, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_6__["NgIf"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["TemplateRef"]], {
          ngIf: [0, "ngIf"]
        }, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\n   "])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](16777216, null, null, 1, null, View_HealthMorCellComponent_4)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](6, 16384, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_6__["NgIf"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["TemplateRef"]], {
          ngIf: [0, "ngIf"]
        }, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\n"]))], function (_ck, _v) {
          var _co = _v.component;
          var currVal_0 = !_co.data.get(_v.context.$implicit);

          _ck(_v, 3, 0, currVal_0);

          var currVal_1 = _co.data.get(_v.context.$implicit);

          _ck(_v, 6, 0, currVal_1);
        }, null);
      }

      function View_HealthMorCellComponent_0(_l) {
        return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\n"])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](16777216, null, null, 1, null, View_HealthMorCellComponent_1)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](2, 16384, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_6__["NgIf"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["TemplateRef"]], {
          ngIf: [0, "ngIf"]
        }, null), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵted"](-1, null, ["\n"])), (_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵand"](16777216, null, null, 1, null, View_HealthMorCellComponent_2)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](5, 278528, null, 0, _angular_common__WEBPACK_IMPORTED_MODULE_6__["NgForOf"], [_angular_core__WEBPACK_IMPORTED_MODULE_1__["ViewContainerRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["TemplateRef"], _angular_core__WEBPACK_IMPORTED_MODULE_1__["IterableDiffers"]], {
          ngForOf: [0, "ngForOf"]
        }, null)], function (_ck, _v) {
          var _co = _v.component;
          var currVal_0 = _co.shape;

          _ck(_v, 2, 0, currVal_0);

          var currVal_1 = _co.keys;

          _ck(_v, 5, 0, currVal_1);
        }, null);
      }

      function View_HealthMorCellComponent_Host_0(_l) {
        return _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵvid"](0, [(_l()(), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵeld"](0, 0, null, null, 1, "vsan-health-mor-cell", [], null, null, null, View_HealthMorCellComponent_0, RenderType_HealthMorCellComponent)), _angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵdid"](1, 49152, null, 0, _health_mor_cell_component__WEBPACK_IMPORTED_MODULE_7__["HealthMorCellComponent"], [_service_navigation_navigation_service__WEBPACK_IMPORTED_MODULE_8__["NavigationService"]], null, null)], null, null);
      }

      var HealthMorCellComponentNgFactory = /*@__PURE__*/_angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵccf"]("vsan-health-mor-cell", _health_mor_cell_component__WEBPACK_IMPORTED_MODULE_7__["HealthMorCellComponent"], View_HealthMorCellComponent_Host_0, {
        missingNameLabel: "missingNameLabel",
        data: "data",
        enableActionLink: "enableActionLink"
      }, {}, []);
      /***/

    },

    /***/
    "uxYv":
    /*!*************************************************************************!*\
      !*** ./src/app/vsan/common/component/cell/health-mor-cell.component.ts ***!
      \*************************************************************************/

    /*! exports provided: HealthMorCellComponent */

    /***/
    function uxYv(module, __webpack_exports__, __webpack_require__) {
      "use strict";

      __webpack_require__.r(__webpack_exports__);
      /* harmony export (binding) */


      __webpack_require__.d(__webpack_exports__, "HealthMorCellComponent", function () {
        return HealthMorCellComponent;
      });
      /* harmony import */


      var _service_managed_object__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
      /*! @service/managed-object */
      "sNBm");
      /* harmony import */


      var _navigation_navigation_service__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
      /*! @navigation/navigation.service */
      "Qw2S");
      /* harmony import */


      var _util_vsan_util__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(
      /*! @util/vsan-util */
      "UODZ");

      var HealthMorCellComponent = /*#__PURE__*/function () {
        function HealthMorCellComponent(navigationService) {
          var _this = this;

          _classCallCheck(this, HealthMorCellComponent);

          this.navigationService = navigationService;
          this.COMMA_SEPARATOR = ",&nbsp;";
          this.enableActionLink = true;

          this.navigateTo = function (objectId) {
            // TODO akolov: when the client SDK introduce API for checking if the context is modal,
            // use it to prevent the error log: API should be called within the context of a modal dialog
            _this.navigationService.navigateToAndCloseModal(_navigation_navigation_service__WEBPACK_IMPORTED_MODULE_1__["PlatformExtension"].LAST_VISITED_PAGE, objectId);
          };
        }

        _createClass(HealthMorCellComponent, [{
          key: "data",
          get: function get() {
            return this._data;
          },
          set: function set(val) {
            this._data = val;
            this.keys = val.keys();
          }
        }, {
          key: "shape",
          get: function get() {
            var _a;

            return ((_a = this.data) === null || _a === void 0 ? void 0 : _a.size) === 1 ? _service_managed_object__WEBPACK_IMPORTED_MODULE_0__["ManagedObjectUtils"].getObjectTypeIcon(this.data.keys().next().value) : "";
          }
        }, {
          key: "getMissingEntityLabel",
          value: function getMissingEntityLabel(uid) {
            if (!!this.missingNameLabel) {
              return this.missingNameLabel;
            }

            var moRef = _service_managed_object__WEBPACK_IMPORTED_MODULE_0__["ManagedObject"].fromUid(uid);

            var typeName = _service_managed_object__WEBPACK_IMPORTED_MODULE_0__["ManagedObjectUtils"].getObjectTypeName(moRef);

            return _util_vsan_util__WEBPACK_IMPORTED_MODULE_2__["VsanUiUtils"].getString("vsan.common.component.morcell.entity.missing.name", typeName, moRef.value);
          }
        }, {
          key: "showComma",
          value: function showComma(index) {
            return index < this.data.size - 1;
          }
        }]);

        return HealthMorCellComponent;
      }();
      /***/

    }
  }]);
})();
//# sourceMappingURL=32-es5.js.map